import { useState } from 'react'
import { ArrowRight, ChevronDown, Dna, GitBranch, FileText, RotateCcw, Menu, X, ShieldCheck, Database, Target, UserRound, SlidersHorizontal, CircleCheck, Activity, ScanLine, Pill, HeartPulse, Brain, Microscope } from 'lucide-react'

const cases = [
 ['Rare & undiagnosed disease','Computational investigation of suspected genetic disease from WES/WGS data, phenotype and family information.',['WES / WGS','Phenotype matching','Variant prioritisation'],FileText],
 ['Hereditary cancer','Germline analysis to identify and prioritise variants in genes associated with inherited cancer susceptibility.',['Germline analysis','Cancer genes','Evidence review'],Activity],
 ['Clinical oncology','Somatic genomic analysis to characterise tumour alterations and support molecular profiling workflows.',['Somatic variants','CNV / SV','Molecular profiling'],ScanLine],
 ['Pharmacogenomics','Analyse genomic variants associated with medication response and organise supporting pharmacogenomic evidence.',['Genotype analysis','Gene–drug evidence','Reporting'],Pill],
 ['Inherited cardiovascular disease','Support investigation of genetic causes of cardiomyopathies, arrhythmias and inherited cardiac disorders.',['Gene panels','WES / WGS','Inheritance'],HeartPulse],
 ['Neurogenetics','Analyse genomic data for neurological and developmental conditions using phenotype- and gene-driven prioritisation.',['Epilepsy','Developmental disorders','Gene prioritisation'],Brain],
 ['Mitochondrial genomics','Computational analysis of mitochondrial variation, including heteroplasmy and disease-associated variants.',['mtDNA','Heteroplasmy','Annotation'],Dna],
 ['CNV & structural variants','Detect and characterise larger genomic alterations that can be missed by small-variant analysis.',['CNVs','SVs','Rearrangements'],Microscope],
 ['Clinical genomic reanalysis','Reanalyse historical cases as annotation databases, evidence and gene–disease knowledge evolve.',['Case reanalysis','Updated evidence','Reprioritisation'],RotateCcw],
]
const faqs=[['What sequencing data can you analyse?','Workflows can be designed around WES, WGS, targeted panels and other sequencing outputs. The pipeline depends on assay type, file format, coverage and the clinical question.'],['Do you diagnose patients?','No. AfroGenomics provides computational analysis and interpretation-support infrastructure. Clinical diagnosis, counselling and final clinical decisions remain with appropriately qualified professionals.'],['Can you work with an existing laboratory?','Yes. AfroGenomics is designed to sit alongside existing sequencing and laboratory workflows.'],['Can historical cases be reanalysed?','Yes. Historical datasets can be processed against updated annotations, evidence and gene–disease knowledge.']]
function Brand(){return <div className="brand"><svg viewBox="0 0 48 58" className="brand-dna"><path d="M34 4C17 14 10 23 12 33c2 10 10 14 22 21M14 8c13 5 20 12 21 20 1 9-5 17-17 25M18 14l14 5M13 23l20 5M14 32l15 4M19 42l13 5" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><circle cx="7" cy="23" r="2.7" fill="currentColor"/><circle cx="8" cy="34" r="2.2" fill="currentColor"/></svg><div><strong>AfroGenomics</strong><small>CLINICAL GENOMICS COMPUTING</small></div></div>}
function App(){const[menu,setMenu]=useState(false),[faq,setFaq]=useState<number|null>(null);const go=(id:string)=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};return <div>
<header><div className="container nav"><a href="#home"><Brand/></a><div className={'links '+(menu?'open':'')}><button className="active" onClick={()=>go('home')}>Home</button><button onClick={()=>go('platform')}>Platform</button><button onClick={()=>go('use-cases')}>Clinical Use Cases</button><button onClick={()=>go('workflow')}>How It Works</button><button onClick={()=>go('technology')}>Technology</button><button onClick={()=>go('about')}>About</button><button className="talk" onClick={()=>go('contact')}>Talk to Us <ArrowRight size={15}/></button></div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
<main>
<section className="hero" id="home"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">CLINICAL GENOMICS <span>•</span> COMPUTATIONAL ANALYSIS</div><h1>From genomic data<br/>to <em>clinical evidence.</em></h1><p>AfroGenomics provides computational analysis and interpretation support for clinical sequencing data, helping <b>laboratories and healthcare teams</b> identify, prioritise and investigate clinically relevant genomic variation.</p><div className="actions"><button className="primary" onClick={()=>go('use-cases')}>Explore Clinical Use Cases <ArrowRight size={17}/></button><button className="how" onClick={()=>go('workflow')}><span>▷</span> How It Works</button></div><div className="metrics"><div><Dna/><b>WES / WGS</b><small>Whole Exome &<br/>Whole Genome</small></div><div><GitBranch/><b>Variant Analysis</b><small>From raw data<br/>to insights</small></div><div><FileText/><b>Clinical Interpretation<br/>Support</b><small>Evidence-based<br/>prioritisation</small></div><div><RotateCcw/><b>Genomic Reanalysis</b><small>New evidence.<br/>New answers.</small></div></div></div><div className="hero-image"><img src="/assets/hero-reference.png" alt="Genomic analysis visualization"/></div></div></section>
<section className="challenge" id="platform"><div className="container challenge-grid"><div><div className="eyebrow">THE CHALLENGE</div><h2>Sequencing generates data.<br/>Clinical genomics <em>needs answers.</em></h2><p>Modern sequencing can generate millions of genomic observations. The challenge is determining which findings matter, which require further investigation, and what evidence supports them.</p><p>AfroGenomics provides the computational workflows that sit between sequencing and clinical review.</p></div><div><div className="mini-pipeline">{[['FASTQ / BAM / VCF',FileText],['QC',CircleCheck],['Alignment',SlidersHorizontal],['Variant Calling',Dna],['Annotation',FileText],['Evidence',Database],['Prioritisation',Target],['Clinical Review',UserRound]].map(([t,I])=>{const C=I as any;return <div><C size={19}/><b>{t as string}</b></div>})}</div><img className="pipeline-image" src="/assets/pipeline-reference.png" alt="Clinical genomic computational workflow"/></div></div></section>
<section className="cases" id="use-cases"><div className="container"><div className="section-head"><div><div className="eyebrow">CLINICAL USE CASES</div><h2>Computational support<br/>for <em>clinical genomics.</em></h2></div><p>Focused on the clinical questions where sequencing data needs rigorous analysis, evidence organisation and structured review.</p></div><div className="case-grid">{cases.map(([t,tx,tags,I])=>{const C=I as any;return <article className="case"><div className="icon"><C size={20}/></div><h3>{t as string}</h3><p>{tx as string}</p><div className="tags">{(tags as string[]).map(x=><span>{x}</span>)}</div><button onClick={()=>go('contact')}>Discuss this use case <ArrowRight size={13}/></button></article>})}</div></div></section>
<section className="workflow" id="workflow"><div className="container"><div className="center"><div className="eyebrow">HOW IT WORKS</div><h2>From sequence<br/>to <em>clinical review.</em></h2><p>A transparent computational workflow designed around quality, reproducibility and traceability.</p></div><div className="steps">{[['01','Sequence','FASTQ / BAM / VCF'],['02','Analyse','QC • alignment • variant calling'],['03','Interpret','annotation • evidence • prioritisation'],['04','Review','structured findings for clinical review']].map(s=><div><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></div></section>
<section className="technology" id="technology"><div className="container tech"><div><div className="eyebrow">TECHNOLOGY</div><h2>Built on rigorous<br/><em>bioinformatics.</em></h2><p>Reproducible workflows can combine established genomics tooling with cloud or HPC infrastructure, selected around the assay and clinical question.</p><div className="pills">{['Nextflow','Docker / Apptainer','Python / R','VEP','ClinVar','gnomAD','FastQC / MultiQC','Cloud / HPC'].map(x=><span>{x}</span>)}</div></div><div className="terminal"><div className="termbar">● ● ● <span>afrogenomics / clinical-workflow</span></div><pre>$ workflow run clinical_wes{`\n`}Loading reference + annotation databases…{`\n`}✓ quality control complete{`\n`}✓ variant analysis complete{`\n`}✓ evidence aggregation complete{`\n`}→ 24 candidate variants prioritised{`\n`}<b>clinical_review / ready</b></pre></div></div></section>
<section className="about" id="about"><div className="container about-grid"><div className="africa"><Dna size={110}/><span>AFRICA</span></div><div><div className="eyebrow">WHY AFRICA</div><h2>Clinical genomics<br/><em>needs African context.</em></h2><p>African populations remain underrepresented in many genomic datasets. AfroGenomics is being built to strengthen the computational infrastructure available to African clinical genomics while developing population-aware capabilities over time.</p><div className="principles"><div><b>01</b>Population-aware analysis</div><div><b>02</b>Responsible data stewardship</div><div><b>03</b>Local scientific capacity</div></div></div></div></section>
<section className="faq"><div className="container faq-grid"><div><div className="eyebrow">FAQ</div><h2>Questions,<br/><em>answered.</em></h2></div><div>{faqs.map(([q,a],i)=><div className="faqrow"><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span><ChevronDown size={17}/></button>{faq===i&&<p>{a}</p>}</div>)}</div></div></section>
<section className="contact" id="contact"><div className="container contact-grid"><div><div className="eyebrow">START A CONVERSATION</div><h2>Have a clinical genomics workflow?<br/><em>Let's build the computational layer.</em></h2><p>Tell us what you sequence, the clinical question you are solving and where your workflow needs computational support.</p></div><form onSubmit={e=>e.preventDefault()}><label>Name<input placeholder="Your name"/></label><label>Organisation<input placeholder="Laboratory, hospital or organisation"/></label><label>Work email<input type="email" placeholder="you@organisation.com"/></label><label>What are you working on?<textarea rows={4} placeholder="e.g. WES rare disease workflow…"/></label><button className="primary">Discuss the workflow <ArrowRight size={16}/></button><small><ShieldCheck size={12}/> No automated clinical decisions are made here.</small></form></div></section>
</main><footer><div className="container foot"><Brand/><p>Computational genomics for clinical workflows in Africa.</p><div><button onClick={()=>go('platform')}>Platform</button><button onClick={()=>go('use-cases')}>Use cases</button><button onClick={()=>go('technology')}>Technology</button><button onClick={()=>go('contact')}>Contact</button></div></div><div className="container copy">© {new Date().getFullYear()} AfroGenomics <span>Clinical genomics • Computational analysis</span></div></footer></div>}
export default App
